
site_name: Architalia 🇮🇹
repo_url: https://github.com/architalia/mkdocs-material
repo_name: architalia/mkdocs-material
edit_uri: edit/main/docs/

theme:
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  logo: assets/logo.png
  favicon: images/logo.png
  name: material
  language: it
  font:
    text: Ubuntu 
    code: Ubuntu mono
  features:
    - navigation.footer
    - navigation.tabs
    - content.action.edit
    
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ArchItalia
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/architalia
    - icon: fontawesome/brands/mastodon
      link: https://  
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@ArchItalia
      
extra_css:
  - stylesheets/extra.css
      
    
copyright: Copyright &copy; 2023 Architalia
  
plugins:
  - git-committers:
      repository: architalia/mkdocs-material
      branch: main






